### ISSUE TITLE
io_test fails.

### ISSUE THREAD

**Issue by tmhuysen** [GQCG/cpputil#2] opened 2018-03-21 12:24 UTC
When making test the following occurs.
  `Start 1: io_test
1/2 Test #1: io_test ..........................***Failed    0.03 sec`  
When building and running with Clion it did not fail the first time, however building and running again resulted in failure at :
`tests/io_test.cpp:57: error: in "read_array_from_file_example": check cpputil::linalg::areEqual(T, T_ref, 1.0e-8) has failed`

My best bet is that the default precision isn't reliable up to 1.0e-8.

**Comment by lelemmen** [comment] 2018-03-22 16:55
I believe the issue is fixed in PR #3. Can you confirm?

**Closed** 2018-03-22 17:04 UTC
